import { createClient } from 'npm:@supabase/supabase-js@2'
import { analyzeText, type Candidate } from '../_shared/analyzer.ts'
import { aiProviderConfigured, analyzeWithAi } from '../_shared/aiProvider.ts'
import { appointmentStartUtc, learnedAppointmentConfidence } from '../_shared/appointmentTime.ts'

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})
const merge=(rules:Candidate[],ai:Candidate[],allowMultiple:boolean)=>{const map=new Map<string,Candidate>();for(const x of [...ai,...rules]){const old=map.get(x.type);if(!old||x.confidence>old.confidence)map.set(x.type,x)}const out=[...map.values()].sort((a,b)=>b.confidence-a.confidence);return allowMultiple?out:out.slice(0,1)}

Deno.serve(async (req) => {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 })
  const started=Date.now();const secret=Deno.env.get('WORKER_SECRET')??''
  if(!secret)return new Response('Worker not configured',{status:503});if(req.headers.get('x-worker-secret')!==secret)return new Response('Unauthorized',{status:401})
  const body=await req.json().catch(()=>({})) as {message_id?:string;source?:'message'|'reprocess'};if(!body.message_id)return json({error:'message_id required'},400)
  const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??Deno.env.get('SUPABASE_SECRET_KEY')!);const{data:message,error}=await supabase.from('messages').select('*').eq('id',body.message_id).single();if(error||!message)return json({error:'message not found'},404)
  let runId:string|undefined;let engine='rules-v1';let fallbackUsed=false;let provider:string|undefined;let model:string|undefined;let promptTokens=0;let completionTokens=0;let totalTokens=0;let estimatedCostUsd=0
  try{
    await supabase.from('message_jobs').update({status:'processing',last_attempt_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('message_id',message.id)
    const[{data:policy},{data:settings},{data:aiAccess}]=await Promise.all([supabase.from('analysis_policies').select('*').eq('company_id',message.company_id).maybeSingle(),supabase.from('company_settings').select('*').eq('company_id',message.company_id).maybeSingle(),supabase.from('platform_ai_company_access').select('release_state').eq('company_id',message.company_id).maybeSingle()])
    if(!message.eligible_for_ai||!message.body_text){const{error:skipRunError}=await supabase.from('analysis_runs').insert({company_id:message.company_id,message_id:message.id,source:body.source??'message',engine,status:'skipped',duration_ms:Date.now()-started});if(skipRunError)throw new Error(`analysis_run_insert_failed:${skipRunError.code??'unknown'}`);await supabase.from('message_jobs').update({status:'done',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('message_id',message.id);return json({skipped:true})}
    const contextLimit=Math.max(1,Math.min(12,Number(policy?.context_messages??5)));const{data:contextRows}=await supabase.from('messages').select('id,body_text,provider_timestamp').eq('conversation_id',message.conversation_id).eq('message_type','text').lt('created_at',message.created_at).order('created_at',{ascending:false}).limit(contextLimit);const context=(contextRows??[]).reverse();const contextText=context.map(row=>row.body_text).filter(Boolean).join('\n')
    let memories:Array<{content:string}> = [];if(policy?.use_company_memory!==false||policy?.use_contact_memory!==false){const{data}=await supabase.from('operational_memories').select('content,contact_id').eq('company_id',message.company_id).eq('is_active',true).order('importance',{ascending:false}).order('created_at',{ascending:false}).limit(12);memories=(data??[]).filter((m:any)=>(policy?.use_company_memory!==false&&m.contact_id===null)||(policy?.use_contact_memory!==false&&m.contact_id===message.contact_id))}
    const memoryText=memories.map(m=>m.content).join('\n');const opts={minConfidence:Number(policy?.min_confidence??.65),allowMultiple:policy?.allow_multiple_suggestions!==false,monitors:settings??{}};const rules=analyzeText(message.body_text,contextText,memoryText,opts);let candidates=rules
    const mode=String(policy?.engine_mode??'rules');const wantsAi=policy?.ai_enabled===true&&(mode==='hybrid'||mode==='llm');let aiAllowed=wantsAi&&aiAccess?.release_state!=='locked'&&aiProviderConfigured()
    if(aiAllowed){const day=new Date();day.setUTCHours(0,0,0,0);const{data:usage}=await supabase.from('analysis_runs').select('total_tokens,estimated_cost_usd').eq('company_id',message.company_id).gte('created_at',day.toISOString());const usedTokens=(usage??[]).reduce((n:any,r:any)=>n+Number(r.total_tokens??0),0);const usedCost=(usage??[]).reduce((n:any,r:any)=>n+Number(r.estimated_cost_usd??0),0);aiAllowed=usedTokens<Number(policy?.ai_daily_token_limit??50000)&&usedCost<Number(policy?.ai_daily_cost_limit_usd??1)}
    if(aiAllowed){try{const ai=await analyzeWithAi({text:message.body_text,context:contextText,memory:memoryText,minConfidence:opts.minConfidence,allowMultiple:opts.allowMultiple,maxCandidates:Number(policy?.ai_max_candidates??4)});provider=ai.provider;model=ai.model;promptTokens=ai.usage.promptTokens;completionTokens=ai.usage.completionTokens;totalTokens=ai.usage.totalTokens;estimatedCostUsd=ai.usage.estimatedCostUsd;engine=mode==='hybrid'?'hybrid-v1':'llm-v1';candidates=mode==='hybrid'?merge(rules,ai.candidates,opts.allowMultiple):ai.candidates}catch(e){if(policy?.fallback_to_rules===false&&mode==='llm')throw e;fallbackUsed=true;engine='rules-fallback-v1';candidates=rules}}
    else if(wantsAi){fallbackUsed=true;engine='rules-fallback-v1'}
    const{data:run,error:runError}=await supabase.from('analysis_runs').insert({company_id:message.company_id,message_id:message.id,source:body.source??'message',engine,status:'done',context_count:context.length,memory_count:memories.length,candidates:candidates.length,suggestions_created:0,duration_ms:0,provider,model,prompt_tokens:promptTokens,completion_tokens:completionTokens,total_tokens:totalTokens,estimated_cost_usd:estimatedCostUsd,fallback_used:fallbackUsed}).select('id').single();if(runError||!run?.id)throw new Error(`analysis_run_insert_failed:${runError?.code??'missing_id'}`);runId=run.id
    const timezone=typeof settings?.timezone==='string'?settings.timezone:'America/Manaus'
    const{data:feedbackRows}=policy?.learning_enabled===false?{data:[]} : await supabase.from('analysis_feedback').select('verdict').eq('company_id',message.company_id).eq('suggestion_type','appointment').in('verdict',['correct','incorrect']).order('created_at',{ascending:false}).limit(100)
    const correct=(feedbackRows??[]).filter((row:any)=>row.verdict==='correct').length,incorrect=(feedbackRows??[]).filter((row:any)=>row.verdict==='incorrect').length
    let created=0,autoScheduled=0
    for(const detected of candidates){
      const extracted={...detected.extracted_data} as Record<string,unknown>;const action=detected.type==='appointment'?String(extracted.action??'create'):'create';const startsAt=detected.type==='appointment'?appointmentStartUtc(extracted,message.created_at,timezone):null
      if(startsAt)extracted.starts_at=startsAt
      if(detected.type==='appointment'&&(action==='reschedule'||action==='cancel')&&message.contact_id){const{data:target}=await supabase.from('appointments').select('id,starts_at').eq('company_id',message.company_id).eq('contact_id',message.contact_id).eq('status','scheduled').gte('starts_at',new Date().toISOString()).order('starts_at',{ascending:true}).limit(1).maybeSingle();if(target){extracted.target_appointment_id=target.id;extracted.previous_starts_at=target.starts_at}}
      const learned=learnedAppointmentConfidence(detected.confidence,correct,incorrect,Number(policy?.auto_schedule_min_samples??5));extracted.learned_confidence=learned.confidence;extracted.learning_samples=learned.samples
      const{data:suggestion,error:insertError}=await supabase.from('ai_suggestions').insert({company_id:message.company_id,contact_id:message.contact_id,conversation_id:message.conversation_id,source_message_id:message.id,context_message_ids:context.map(row=>row.id),type:detected.type,title:detected.title,summary:detected.summary,reason:detected.reason,confidence:detected.confidence,extracted_data:extracted}).select('id').single();if(insertError||!suggestion?.id)throw new Error(`suggestion_insert_failed:${insertError?.code??'missing_id'}`);created++
      const canAuto=detected.type==='appointment'&&action==='create'&&Boolean(startsAt)&&policy?.auto_schedule_enabled!==false&&policy?.learning_enabled!==false&&learned.eligible&&learned.confidence>=Number(policy?.auto_schedule_threshold??.95)
      if(canAuto){const{error:appointmentError}=await supabase.from('appointments').insert({company_id:message.company_id,contact_id:message.contact_id,suggestion_id:suggestion.id,title:detected.title,starts_at:startsAt,notes:detected.summary,kind:'appointment'});if(appointmentError)throw new Error(`auto_schedule_failed:${appointmentError.code??'unknown'}`);const{error:resolveError}=await supabase.from('ai_suggestions').update({status:'confirmed',resolved_at:new Date().toISOString()}).eq('id',suggestion.id);if(resolveError)throw new Error(`auto_schedule_resolve_failed:${resolveError.code??'unknown'}`);autoScheduled++;await supabase.from('audit_logs').insert({company_id:message.company_id,action:'appointment_auto_scheduled',entity_type:'ai_suggestion',entity_id:suggestion.id,metadata:{confidence:detected.confidence,learned_confidence:learned.confidence,learning_samples:learned.samples,threshold:Number(policy?.auto_schedule_threshold??.95),starts_at:startsAt}})}
    }
    if(runId)await supabase.from('analysis_runs').update({suggestions_created:created,duration_ms:Date.now()-started}).eq('id',runId);await supabase.from('message_jobs').update({status:'done',last_error:null,failure_class:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('message_id',message.id);await supabase.from('audit_logs').insert({company_id:message.company_id,action:'message_analyzed',entity_type:'message',entity_id:message.id,metadata:{engine,candidates:candidates.length,suggestions_created:created,fallback_used:fallbackUsed,total_tokens:totalTokens,ai_release_state:aiAccess?.release_state??'locked',auto_scheduled:autoScheduled}});return json({ok:true,engine,candidates:candidates.length,suggestions_created:created,fallback_used:fallbackUsed,auto_scheduled:autoScheduled})
  }catch(e){const code=e instanceof Error?e.message||e.name:'analysis_error';try{await supabase.from('analysis_runs').insert({company_id:message.company_id,message_id:message.id,source:body.source??'message',engine,status:'error',duration_ms:Date.now()-started,error_code:String(code).slice(0,120),provider,model,prompt_tokens:promptTokens,completion_tokens:completionTokens,total_tokens:totalTokens,estimated_cost_usd:estimatedCostUsd,fallback_used:fallbackUsed})}catch{}try{const{data:job}=await supabase.from('message_jobs').select('attempts,max_attempts').eq('message_id',message.id).maybeSingle();const attempts=Number(job?.attempts??0)+1;await supabase.from('message_jobs').update({status:'failed',attempts,last_error:String(code).slice(0,240),failure_class:attempts>=Number(job?.max_attempts??3)?'exhausted':'retryable',last_attempt_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('message_id',message.id)}catch{}return json({error:'analysis_failed'},500)}
})
