import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, Clock3, MapPin, Plus, Trash2, X } from 'lucide-react'
import { useCompany } from '../company/CompanyProvider'
import { supabase } from '../lib/supabase'
import { dateTimeLocalToIso, formatDateTime, toDateTimeLocal } from '../lib/format'
import type { Appointment, Contact } from '../lib/operationalTypes'

const kinds = [{v:'appointment',l:'Agendamento'},{v:'visit',l:'Visita'},{v:'delivery',l:'Entrega'},{v:'meeting',l:'Reunião'},{v:'other',l:'Outro'}]

export function AgendaPage() {
  const { currentCompany } = useCompany()
  const [items,setItems]=useState<Appointment[]>([]); const [contacts,setContacts]=useState<Contact[]>([])
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Appointment|null>(null)
  const [title,setTitle]=useState(''); const [startsAt,setStartsAt]=useState(''); const [endsAt,setEndsAt]=useState(''); const [address,setAddress]=useState(''); const [notes,setNotes]=useState(''); const [contactId,setContactId]=useState(''); const [kind,setKind]=useState('appointment'); const [busy,setBusy]=useState(false)

  const load=useCallback(async()=>{ if(!currentCompany)return; setLoading(true);setError(''); try{const [a,c]=await Promise.all([supabase.from('appointments').select('*').eq('company_id',currentCompany.id).order('starts_at',{ascending:true}),supabase.from('contacts').select('*').eq('company_id',currentCompany.id).order('name')]);if(a.error)throw a.error;if(c.error)throw c.error;setItems((a.data??[]) as Appointment[]);setContacts((c.data??[]) as Contact[])}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a agenda.')}finally{setLoading(false)}},[currentCompany])
  useEffect(()=>{void load()},[load])
  const upcoming=useMemo(()=>items.filter(i=>i.status!=='cancelled'&&new Date(i.starts_at).getTime()>=Date.now()-86400000),[items])

  function openNew(){setEditing(null);setTitle('');setStartsAt(toDateTimeLocal(new Date(Date.now()+3600000).toISOString()));setEndsAt('');setAddress('');setNotes('');setContactId('');setKind('appointment');setShowForm(true)}
  function openEdit(item:Appointment){setEditing(item);setTitle(item.title);setStartsAt(toDateTimeLocal(item.starts_at));setEndsAt(toDateTimeLocal(item.ends_at));setAddress(item.address??'');setNotes(item.notes??'');setContactId(item.contact_id??'');setKind(item.kind??'appointment');setShowForm(true)}
  async function save(e:FormEvent){e.preventDefault();if(!currentCompany)return;setBusy(true);setError('');try{const payload={company_id:currentCompany.id,title:title.trim(),starts_at:dateTimeLocalToIso(startsAt),ends_at:dateTimeLocalToIso(endsAt),address:address.trim()||null,notes:notes.trim()||null,contact_id:contactId||null,kind};if(editing){const {error:err}=await supabase.from('appointments').update(payload).eq('id',editing.id).eq('company_id',currentCompany.id);if(err)throw err}else{const {error:err}=await supabase.from('appointments').insert(payload);if(err)throw err}setShowForm(false);await load()}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar.')}finally{setBusy(false)}}
  async function setStatus(item:Appointment,status:string){if(!currentCompany)return;const {error:err}=await supabase.from('appointments').update({status}).eq('id',item.id).eq('company_id',currentCompany.id);if(err)setError(err.message);else await load()}
  async function remove(item:Appointment){if(!currentCompany||!confirm('Excluir este compromisso?'))return;const {error:err}=await supabase.from('appointments').delete().eq('id',item.id).eq('company_id',currentCompany.id);if(err)setError(err.message);else await load()}
  const contactName=(id:string|null)=>contacts.find(c=>c.id===id)?.name

  return <section><div className="page-heading"><div><span className="eyebrow">AGENDA INTERNA</span><h1>Compromissos</h1><p>Sua agenda principal, independente do Google Agenda e pronta para integração futura.</p></div><button className="primary-button action-button" onClick={openNew}><Plus size={17}/>Novo compromisso</button></div>
    {error&&<div className="form-error page-message">{error}</div>}
    <div className="filter-strip"><span className="status-pill">{upcoming.length} próximos</span><span className="muted">Cancelados ficam no histórico e não aparecem como pendência.</span></div>
    <div className="panel-card no-pad">{loading?<div className="loading-block">Carregando agenda...</div>:upcoming.length?<div className="record-list">{upcoming.map(item=><article className="record-row" key={item.id}><div className="date-badge"><strong>{new Date(item.starts_at).getDate().toString().padStart(2,'0')}</strong><span>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(item.starts_at))}</span></div><div className="record-main"><div className="record-title"><strong>{item.title}</strong><span className="mini-status">{kinds.find(k=>k.v===(item.kind??'appointment'))?.l}</span></div><div className="record-meta"><span><Clock3 size={14}/>{formatDateTime(item.starts_at)}</span>{item.address&&<span><MapPin size={14}/>{item.address}</span>}{contactName(item.contact_id)&&<span>{contactName(item.contact_id)}</span>}</div>{item.notes&&<p>{item.notes}</p>}</div><div className="row-actions"><button className="secondary-button" onClick={()=>openEdit(item)}>Editar</button><button className="icon-button small success" onClick={()=>void setStatus(item,'completed')} title="Concluir"><Check size={16}/></button><button className="icon-button small" onClick={()=>void setStatus(item,'cancelled')} title="Cancelar"><X size={16}/></button><button className="icon-button small danger" onClick={()=>void remove(item)} title="Excluir"><Trash2 size={16}/></button></div></article>)}</div>:<div className="big-empty"><CalendarDays size={34}/><h3>Sua agenda está livre</h3><p>Crie um compromisso manualmente. Quando a Secretária detectar agendamentos, eles também aparecerão aqui.</p><button className="primary-button action-button" onClick={openNew}><Plus size={17}/>Criar compromisso</button></div>}</div>
    {showForm&&<div className="modal-backdrop" onClick={()=>setShowForm(false)}><form className="modal-card" onClick={e=>e.stopPropagation()} onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{editing?'EDITAR':'NOVO'}</span><h2>{editing?'Editar compromisso':'Novo compromisso'}</h2></div><button type="button" className="icon-button" onClick={()=>setShowForm(false)}><X size={18}/></button></div><div className="form-stack"><label><span>Título</span><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Visita técnica no cliente"/></label><div className="form-grid two"><label><span>Início</span><input required type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label><span>Fim · opcional</span><input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label></div><div className="form-grid two"><label><span>Tipo</span><select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(k=><option value={k.v} key={k.v}>{k.l}</option>)}</select></label><label><span>Cliente · opcional</span><select value={contactId} onChange={e=>setContactId(e.target.value)}><option value="">Sem cliente</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name||c.phone||'Cliente sem nome'}</option>)}</select></label></div><label><span>Endereço</span><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Local do compromisso"/></label><label><span>Observações</span><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalhes úteis para lembrar depois"/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Salvando...':'Salvar'}</button></div></form></div>}
  </section>
}
