import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Mail, MessageCircle, Phone, Plus, Search, UserRound, X } from 'lucide-react'
import { useCompany } from '../company/CompanyProvider'
import { supabase } from '../lib/supabase'
import type { Contact } from '../lib/operationalTypes'

export function ClientsPage(){
  const{currentCompany}=useCompany();const[items,setItems]=useState<Contact[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[showForm,setShowForm]=useState(false);const[editing,setEditing]=useState<Contact|null>(null);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{if(!currentCompany)return;setLoading(true);setError('');const{data,error:err}=await supabase.from('contacts').select('*').eq('company_id',currentCompany.id).order('name',{ascending:true,nullsFirst:false});if(err)setError(err.message);else setItems((data??[]) as Contact[]);setLoading(false)},[currentCompany]);useEffect(()=>{void load()},[load])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(i=>[i.name,i.phone,i.email,i.notes].some(v=>v?.toLowerCase().includes(q))):items},[items,query])
  function openNew(){setEditing(null);setName('');setPhone('');setEmail('');setNotes('');setShowForm(true)}function openEdit(i:Contact){setEditing(i);setName(i.name??'');setPhone(i.phone??'');setEmail(i.email??'');setNotes(i.notes??'');setShowForm(true)}
  async function save(e:FormEvent){e.preventDefault();if(!currentCompany)return;setBusy(true);setError('');try{const payload={company_id:currentCompany.id,name:name.trim()||null,phone:phone.trim()||null,email:email.trim()||null,notes:notes.trim()||null};if(editing){const{error:err}=await supabase.from('contacts').update(payload).eq('id',editing.id).eq('company_id',currentCompany.id);if(err)throw err}else{const{error:err}=await supabase.from('contacts').insert({...payload,whatsapp_id:phone.trim()||`manual:${crypto.randomUUID()}`});if(err)throw err}setShowForm(false);await load()}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar o cliente.')}finally{setBusy(false)}}
  return <section><div className="page-heading"><div><span className="eyebrow">CLIENTES</span><h1>Relacionamento sem CRM pesado</h1><p>Dados essenciais, histórico operacional e vínculo com tarefas, agenda e conversas.</p></div><button className="primary-button action-button" onClick={openNew}><Plus size={17}/>Novo cliente</button></div>{error&&<div className="form-error page-message">{error}</div>}<div className="toolbar-card"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, telefone, e-mail ou anotação"/></div><span className="muted">{filtered.length} cliente(s)</span></div>
    <div className="cards-grid clients-grid">{loading?<div className="panel-card">Carregando...</div>:filtered.length?filtered.map(item=><article className="client-card" key={item.id} onClick={()=>openEdit(item)}><div className="client-avatar">{(item.name?.[0]||'?').toUpperCase()}</div><div className="client-content"><strong>{item.name||'Cliente sem nome'}</strong><div className="client-lines">{item.phone&&<span><Phone size={14}/>{item.phone}</span>}{item.email&&<span><Mail size={14}/>{item.email}</span>}{item.whatsapp_id&&<span><MessageCircle size={14}/>WhatsApp identificado</span>}</div>{item.notes&&<p>{item.notes}</p>}</div></article>):<div className="big-empty panel-card full-span"><UserRound size={34}/><h3>Nenhum cliente cadastrado</h3><p>Cadastre manualmente agora. Depois, novos contatos também poderão nascer das conversas do WhatsApp.</p><button className="primary-button action-button" onClick={openNew}><Plus size={17}/>Cadastrar cliente</button></div>}</div>
    {showForm&&<div className="modal-backdrop" onClick={()=>setShowForm(false)}><form className="modal-card" onClick={e=>e.stopPropagation()} onSubmit={save}><div className="modal-head"><div><span className="eyebrow">CLIENTE</span><h2>{editing?'Editar cliente':'Novo cliente'}</h2></div><button type="button" className="icon-button" onClick={()=>setShowForm(false)}><X size={18}/></button></div><div className="form-stack"><label><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do cliente"/></label><div className="form-grid two"><label><span>Telefone</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(00) 00000-0000"/></label><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="cliente@email.com"/></label></div><label><span>Anotações</span><textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Preferências, endereço, observações importantes..."/></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?'Salvando...':'Salvar cliente'}</button></div></form></div>}
  </section>}
