import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Beaker, Building2, Database, GitBranch, MessageCircle, RefreshCw, ServerCog, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { formatDateTime } from '../lib/format'

type Overview={companies:number;users:number;whatsapp_connected:number;whatsapp_total:number;pending_suggestions:number;open_work:number;messages:number;analysis_runs_24h?:number;analysis_errors_24h?:number;pending_jobs?:number;failed_jobs?:number;exhausted_jobs?:number}
type CompanyRow={id:string;name:string;created_at:string;member_count:number;whatsapp_status:string;open_items:number}
type IntegrationRow={key:string;label:string;provider:string;status:'healthy'|'paused'|'attention'|'unknown';version:string|null;public_config:Record<string,unknown>;notes:string|null;last_checked_at:string|null;updated_at:string}
type ActivityRow={id:number;action:string;target_company_id:string|null;metadata:Record<string,unknown>;created_at:string}
type AiUsage={ai_companies:number;hybrid_companies:number;llm_companies:number;tokens_24h:number;cost_24h_usd:number;fallbacks_24h:number}
type Quality={feedback_30d:number;correct_30d:number;incorrect_30d:number;accuracy_30d:number}
type AiAccessRow={company_id:string;company_name:string;release_state:'locked'|'pilot'|'enabled';ai_enabled:boolean;engine_mode:string;updated_at:string}
type EvalMaster={evaluation_runs_30d:number;companies_with_baseline:number;regressions_latest_24h:number;ai_locked:number;ai_pilot:number;ai_enabled:number}

const integrationIcon=(key:string)=>key==='meta_whatsapp'?MessageCircle:key==='github'?GitBranch:key==='vercel'?ServerCog:Database
const statusLabel:Record<IntegrationRow['status'],string>={healthy:'Saudável',paused:'Pausado',attention:'Atenção',unknown:'Não verificado'}

export function MasterPage(){
  const[role,setRole]=useState<string|null>(null);const[aiAccess,setAiAccess]=useState<AiAccessRow[]>([]);const[evalMaster,setEvalMaster]=useState<EvalMaster|null>(null);const[releaseBusy,setReleaseBusy]=useState('');const[quality,setQuality]=useState<Quality|null>(null);const[overview,setOverview]=useState<Overview|null>(null);const[aiUsage,setAiUsage]=useState<AiUsage|null>(null);const[companies,setCompanies]=useState<CompanyRow[]>([]);const[integrations,setIntegrations]=useState<IntegrationRow[]>([]);const[activity,setActivity]=useState<ActivityRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const roleResult=await supabase.rpc('get_my_platform_role');if(roleResult.error)throw roleResult.error;const currentRole=(roleResult.data as string|null)??null;setRole(currentRole);if(!currentRole){setOverview(null);setCompanies([]);setIntegrations([]);setActivity([]);return}const[o,c,i,a,ai,q,access,ev]=await Promise.all([supabase.rpc('platform_master_overview'),supabase.rpc('platform_master_companies',{limit_rows:100}),supabase.rpc('platform_master_integrations'),supabase.rpc('platform_master_activity',{limit_rows:25}),supabase.rpc('platform_master_ai_usage'),supabase.rpc('platform_master_quality'),supabase.rpc('platform_master_ai_access'),supabase.rpc('platform_master_ai_evaluation')]);if(o.error)throw o.error;if(c.error)throw c.error;if(i.error)throw i.error;if(a.error)throw a.error;setOverview(o.data as Overview);setCompanies((c.data??[]) as CompanyRow[]);setIntegrations((i.data??[]) as IntegrationRow[]);setActivity((a.data??[]) as ActivityRow[]);if(!ai.error)setAiUsage((ai.data??null) as AiUsage|null);if(!q.error)setQuality((q.data??null) as Quality|null);if(!access.error)setAiAccess((access.data??[]) as AiAccessRow[]);if(!ev.error)setEvalMaster((ev.data??null) as EvalMaster|null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a Área Master.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])

  async function changeRelease(companyId:string,state:AiAccessRow['release_state']){if(role!=='master')return;setReleaseBusy(companyId);const{error:e}=await supabase.rpc('platform_master_set_ai_access',{target_company_id:companyId,target_state:state,target_note:'Alterado pela Área Master'});if(e)setError(e.message);else await load();setReleaseBusy('')}
  const visibleCompanies=useMemo(()=>{const q=query.trim().toLowerCase();return q?companies.filter(c=>c.name.toLowerCase().includes(q)):companies},[companies,query])
  if(loading)return <section><div className="panel-card">Carregando Área Master...</div></section>
  if(!role)return <section><div className="big-empty panel-card"><ShieldCheck size={38}/><h2>Área administrativa restrita</h2><p>Seu usuário não possui função administrativa da plataforma. As permissões Master são independentes das permissões de cada empresa.</p></div></section>

  return <section>
    <div className="page-heading master-heading"><div><span className="eyebrow">ÁREA MASTER · {role.toUpperCase()}</span><h1>Comando da plataforma</h1><p>Empresas, integrações, saúde operacional e auditoria sem expor qualquer segredo no navegador.</p></div><button className="secondary-button master-refresh" onClick={()=>void load()}><RefreshCw size={16}/>Atualizar</button></div>
    {error&&<div className="form-error page-message">{error}</div>}
    {overview&&<div className="master-stats"><div className="master-stat blue"><span><Building2 size={19}/>Empresas</span><strong>{overview.companies}</strong></div><div className="master-stat violet"><span><UsersRound size={19}/>Usuários</span><strong>{overview.users}</strong></div><div className="master-stat mint"><span><MessageCircle size={19}/>WhatsApp conectado</span><strong>{overview.whatsapp_connected}<small> / {overview.whatsapp_total}</small></strong></div><div className="master-stat amber"><span><Sparkles size={19}/>Sugestões pendentes</span><strong>{overview.pending_suggestions}</strong></div><div className="master-stat coral"><span><Activity size={19}/>Trabalho aberto</span><strong>{overview.open_work}</strong></div><div className="master-stat navy"><span><Database size={19}/>Mensagens recebidas</span><strong>{overview.messages}</strong></div><div className="master-stat blue"><span><Activity size={19}/>Análises 24h</span><strong>{overview.analysis_runs_24h??0}</strong></div><div className="master-stat coral"><span><ShieldCheck size={19}/>Erros análise</span><strong>{overview.analysis_errors_24h??0}<small> · {overview.pending_jobs??0} fila</small></strong></div><div className="master-stat amber"><span><Activity size={19}/>Falhas na fila</span><strong>{overview.failed_jobs??0}<small> · {overview.exhausted_jobs??0} esgotada(s)</small></strong></div></div>}

    {quality&&<div className="master-stats"><div className="master-stat mint"><span><ShieldCheck size={19}/>Qualidade avaliada</span><strong>{quality.feedback_30d}</strong></div><div className="master-stat violet"><span><Sparkles size={19}/>Precisão humana</span><strong>{quality.feedback_30d?`${Math.round(Number(quality.accuracy_30d)*100)}%`:'—'}</strong></div><div className="master-stat blue"><span><Activity size={19}/>Corretas · 30d</span><strong>{quality.correct_30d}</strong></div><div className="master-stat coral"><span><Activity size={19}/>Incorretas · 30d</span><strong>{quality.incorrect_30d}</strong></div></div>}
    {aiUsage&&<div className="master-stats"><div className="master-stat violet"><span><Sparkles size={19}/>Empresas com IA</span><strong>{aiUsage.ai_companies}</strong></div><div className="master-stat blue"><span><Activity size={19}/>Tokens IA · 24h</span><strong>{Number(aiUsage.tokens_24h).toLocaleString('pt-BR')}</strong></div><div className="master-stat amber"><span><Database size={19}/>Custo estimado · 24h</span><strong>US$ {Number(aiUsage.cost_24h_usd).toFixed(4)}</strong></div><div className="master-stat mint"><span><ShieldCheck size={19}/>Fallbacks · 24h</span><strong>{aiUsage.fallbacks_24h}</strong></div></div>}

    {evalMaster&&<><div className="master-section-title"><div><span className="eyebrow">LIBERAÇÃO DA IA</span><h2>Quality gate antes de produção</h2></div><span className="safe-chip"><ShieldCheck size={14}/>Controle independente da empresa</span></div><div className="master-stats"><div className="master-stat navy"><span><ShieldCheck size={19}/>Bloqueadas</span><strong>{evalMaster.ai_locked}</strong></div><div className="master-stat amber"><span><Sparkles size={19}/>Piloto</span><strong>{evalMaster.ai_pilot}</strong></div><div className="master-stat mint"><span><Sparkles size={19}/>Liberadas</span><strong>{evalMaster.ai_enabled}</strong></div><div className="master-stat blue"><span><Beaker size={19}/>Avaliações · 30d</span><strong>{evalMaster.evaluation_runs_30d}</strong></div><div className="master-stat violet"><span><ShieldCheck size={19}/>Com baseline</span><strong>{evalMaster.companies_with_baseline}</strong></div><div className="master-stat coral"><span><Activity size={19}/>Regressões · 24h</span><strong>{evalMaster.regressions_latest_24h}</strong></div></div><div className="panel-card"><div className="panel-head"><div><span className="eyebrow">EMPRESAS E IA</span><h2>Canal de liberação</h2><p>Mesmo que um proprietário habilite IA nas preferências, chamadas ao provedor só ocorrem quando a plataforma libera a empresa aqui.</p></div></div><div className="master-table"><div className="master-table-head"><span>Empresa</span><span>Modo</span><span>Preferência</span><span>Liberação</span><span>Controle</span></div>{aiAccess.slice(0,20).map(row=><div className="master-table-row" key={row.company_id}><strong>{row.company_name}</strong><span>{row.engine_mode||'rules'}</span><span>{row.ai_enabled?'IA solicitada':'Regras'}</span><span className={`integration-state ${row.release_state==='enabled'?'ok':row.release_state==='pilot'?'attention':'paused'}`}>{row.release_state==='enabled'?'Liberada':row.release_state==='pilot'?'Piloto':'Bloqueada'}</span><span>{role==='master'?<select disabled={releaseBusy===row.company_id} value={row.release_state} onChange={e=>void changeRelease(row.company_id,e.target.value as AiAccessRow['release_state'])}><option value="locked">Bloqueada</option><option value="pilot">Piloto</option><option value="enabled">Liberada</option></select>:<small>Somente Master</small>}</span></div>)}</div></div></>}
    <div className="master-section-title"><div><span className="eyebrow">SAÚDE E INTEGRAÇÕES</span><h2>Serviços que sustentam a Secretária</h2></div><span className="safe-chip"><ShieldCheck size={14}/>Sem segredos no frontend</span></div>
    <div className="integration-health-grid">{integrations.map(item=>{const Icon=integrationIcon(item.key);return <article className={`integration-health-card status-${item.status}`} key={item.key}><div className="integration-health-top"><span className="settings-icon mint"><Icon size={19}/></span><span className={`integration-state ${item.status==='healthy'?'ok':item.status==='paused'?'paused':'attention'}`}>{statusLabel[item.status]}</span></div><h3>{item.label}</h3><p>{item.notes||item.provider}</p><div className="integration-meta"><span>{item.version||item.provider}</span><span>{item.last_checked_at?`Atualizado ${formatDateTime(item.last_checked_at)}`:'Sem verificação recente'}</span></div></article>})}</div>

    <div className="master-grid master-grid-wide"><div className="panel-card master-companies"><div className="panel-head master-company-head"><div><span className="eyebrow">EMPRESAS</span><h2>Operação atual</h2></div><div className="master-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa"/><span className="mini-status">{visibleCompanies.length} exibidas</span></div></div><div className="master-table"><div className="master-table-head"><span>Empresa</span><span>Equipe</span><span>WhatsApp</span><span>Pendências</span><span>Criada</span></div>{visibleCompanies.map(c=><div className="master-table-row" key={c.id}><strong>{c.name}</strong><span>{c.member_count}</span><span className={`integration-state ${c.whatsapp_status==='connected'?'ok':'paused'}`}>{c.whatsapp_status==='connected'?'Conectado':'Pendente'}</span><span>{c.open_items}</span><span>{formatDateTime(c.created_at)}</span></div>)}</div></div>
      <aside className="panel-card master-activity"><div className="panel-head"><div><span className="eyebrow">AUDITORIA MASTER</span><h2>Atividade recente</h2></div></div>{activity.length?<div className="master-activity-list">{activity.map(row=><div className="master-activity-row" key={row.id}><span className="activity-dot"/><div><strong>{row.action.replaceAll('_',' ')}</strong><span>{formatDateTime(row.created_at)}</span></div></div>)}</div>:<div className="inline-empty"><Activity size={28}/><strong>Nenhuma ação administrativa recente</strong><span>Alterações Master auditadas aparecerão aqui.</span></div>}</aside>
    </div>
    <div className="security-note master-security-note"><ShieldCheck size={18}/><span>Tokens, App Secrets, chaves privadas e service-role permanecem em armazenamento seguro. A Área Master trabalha apenas com estado, configuração pública e ações autorizadas.</span></div>
  </section>
}
