import { useCallback, useEffect, useState } from 'react'
import { CalendarPlus, Check, ClipboardPlus, Eye, MessageSquareText, Sparkles, X } from 'lucide-react'
import { useAuth } from '../auth/AuthProvider'
import { useCompany } from '../company/CompanyProvider'
import { supabase } from '../lib/supabase'
import { formatDateTime } from '../lib/format'
import type { Suggestion } from '../lib/operationalTypes'

const labels:Record<Suggestion['type'],string>={appointment:'Agendamento',task:'Tarefa',order:'Pedido',quote:'Orçamento',payment_promise:'Pagamento',follow_up:'Retorno',awaiting_reply:'Aguardando',deadline:'Prazo'}

export function SecretaryPage(){
  const{user}=useAuth();const{currentCompany}=useCompany();const[items,setItems]=useState<Suggestion[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');const[selected,setSelected]=useState<Suggestion|null>(null);const[busy,setBusy]=useState('')
  const load=useCallback(async()=>{if(!currentCompany)return;setLoading(true);setError('');const{data,error:err}=await supabase.from('ai_suggestions').select('*').eq('company_id',currentCompany.id).order('created_at',{ascending:false}).limit(60);if(err)setError(err.message);else setItems((data??[]) as Suggestion[]);setLoading(false)},[currentCompany]);useEffect(()=>{void load()},[load])
  async function resolve(item:Suggestion,status:'confirmed'|'ignored'){if(!currentCompany||!user)return;setBusy(item.id);setError('');setMessage('');try{if(status==='confirmed'){const data=item.extracted_data??{};if(item.type==='appointment'){const starts=typeof data.starts_at==='string'?data.starts_at:new Date(Date.now()+86400000).toISOString();const{error:insertError}=await supabase.from('appointments').insert({company_id:currentCompany.id,contact_id:item.contact_id,suggestion_id:item.id,title:item.title,starts_at:starts,ends_at:typeof data.ends_at==='string'?data.ends_at:null,address:typeof data.address==='string'?data.address:null,notes:item.summary,kind:typeof data.kind==='string'?data.kind:'appointment'});if(insertError)throw insertError}else if(item.type==='task'){const{error:insertError}=await supabase.from('tasks').insert({company_id:currentCompany.id,contact_id:item.contact_id,suggestion_id:item.id,title:item.title,description:item.summary,due_at:typeof data.due_at==='string'?data.due_at:null,priority:'normal'});if(insertError)throw insertError}else if(['order','quote','follow_up','awaiting_reply','deadline'].includes(item.type)){const map:Record<string,string>={order:'order',quote:'quote',follow_up:'follow_up',awaiting_reply:'awaiting_reply',deadline:'deadline'};const{error:insertError}=await supabase.from('work_items').insert({company_id:currentCompany.id,contact_id:item.contact_id,suggestion_id:item.id,type:map[item.type],title:item.title,description:item.summary,due_at:typeof data.due_at==='string'?data.due_at:null,amount:typeof data.amount==='number'?data.amount:null});if(insertError)throw insertError}}
    const{error:updateError}=await supabase.from('ai_suggestions').update({status,resolved_by:user.id,resolved_at:new Date().toISOString()}).eq('id',item.id).eq('company_id',currentCompany.id);if(updateError)throw updateError;setMessage(status==='confirmed'?'Confirmado e organizado.':'Sugestão ignorada.');setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível resolver a sugestão.')}finally{setBusy('')}}
  const pending=items.filter(i=>i.status==='pending');const resolved=items.filter(i=>i.status!=='pending')
  return <section><div className="page-heading"><div><span className="eyebrow">CENTRAL DA SECRETÁRIA</span><h1>Eu encontro. Você decide.</h1><p>Toda sugestão importante fica verificável antes de virar compromisso, tarefa ou trabalho.</p></div><span className="status-pill">Modo observação</span></div>{error&&<div className="form-error page-message">{error}</div>}{message&&<div className="form-success page-message">{message}</div>}
    <div className="secretary-intro"><div className="secretary-orb"><Sparkles size={24}/></div><div><strong>Fluxo preparado para mensagens reais</strong><span>Enquanto a conexão da Meta está pausada, a central permanece funcional e pronta para receber sugestões produzidas pelo motor IA.</span></div></div>
    <div className="section-heading"><div><span className="eyebrow">PRECISA DA SUA ATENÇÃO</span><h2>{pending.length} sugestão(ões) pendente(s)</h2></div></div>
    {loading?<div className="panel-card">Carregando...</div>:pending.length?<div className="cards-stack">{pending.map(item=><article className="attention-card" key={item.id}><div className="attention-main"><div className="suggestion-title-line"><span className="eyebrow">{labels[item.type]}</span>{item.confidence!=null&&<span className="mini-status">{Math.round(item.confidence*100)}% confiança</span>}</div><h3>{item.title}</h3><p>{item.summary||item.reason||'A Secretária identificou algo que pode exigir uma ação.'}</p><small>{formatDateTime(item.created_at)}</small></div><div className="card-actions"><button className="primary-button" disabled={busy===item.id} onClick={()=>void resolve(item,'confirmed')}><Check size={16}/>Confirmar</button><button className="secondary-button" onClick={()=>setSelected(item)}><Eye size={16}/>Ver contexto</button><button className="secondary-button subtle-danger" disabled={busy===item.id} onClick={()=>void resolve(item,'ignored')}><X size={16}/>Ignorar</button></div></article>)}</div>:<div className="big-empty panel-card"><Sparkles size={34}/><h3>Nada aguardando confirmação</h3><p>Quando a Secretária encontrar um agendamento, tarefa, pedido, orçamento ou prazo, ele aparecerá aqui para você decidir.</p></div>}
    {resolved.length>0&&<div className="panel-card secretary-history"><div className="panel-head"><div><span className="eyebrow">HISTÓRICO RECENTE</span><h2>Decisões anteriores</h2></div></div><div className="compact-list">{resolved.slice(0,8).map(item=><div className="compact-row" key={item.id}><div className="list-icon">{item.status==='ignored'?<X size={16}/>:<Check size={16}/>}</div><div className="grow"><strong>{item.title}</strong><span>{labels[item.type]} · {item.status==='ignored'?'Ignorado':'Confirmado'}</span></div></div>)}</div></div>}
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">POR QUE ESTOU VENDO ISSO?</span><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="context-box"><MessageSquareText size={20}/><div><strong>Contexto verificável</strong><p>{selected.reason||selected.summary||'O contexto completo será exibido quando a mensagem de origem estiver disponível.'}</p><small>Mensagem de origem: {selected.source_message_id.slice(0,8)}… · {selected.context_message_ids.length} mensagem(ns) de apoio</small></div></div><div className="conversion-hints"><div><CalendarPlus size={18}/><span>Agendamentos confirmados vão para Agenda.</span></div><div><ClipboardPlus size={18}/><span>Tarefas, pedidos e prazos vão para Trabalho.</span></div></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Fechar</button>{selected.status==='pending'&&<button className="primary-button" onClick={()=>void resolve(selected,'confirmed')}>Confirmar</button>}</div></div></div>}
  </section>}
