import { useEffect, useState } from 'react'
import { BellRing, Download, Smartphone, Volume2 } from 'lucide-react'
import { getDeviceAlertPreferences, notificationSupport, previewAlertSound, requestDeviceNotificationPermission, saveDeviceAlertPreferences, type AlertSound } from '../lib/deviceNotifications'

type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>}
export function DeviceAlertsPanel(){
  const[preferences,setPreferences]=useState(getDeviceAlertPreferences),[permission,setPermission]=useState<NotificationPermission|'unsupported'>(()=>notificationSupport()?Notification.permission:'unsupported'),[installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null),[installed,setInstalled]=useState(()=>window.matchMedia('(display-mode: standalone)').matches)
  useEffect(()=>{const before=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)},done=()=>{setInstalled(true);setInstallPrompt(null)};window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',done)}},[])
  function update(patch:Partial<typeof preferences>){const next={...preferences,...patch};setPreferences(next);saveDeviceAlertPreferences(next)}
  async function activate(){setPermission(await requestDeviceNotificationPermission())}
  async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice}}
  return <div className="settings-card colorful-card device-alert-card"><div className="settings-card-title"><span className="settings-icon coral"><BellRing size={20}/></span><div><h2>Alertas no computador e celular</h2><p>Receba avisos usando outra tela e abra diretamente a situação que precisa ser resolvida.</p></div></div><div className="device-alert-status"><Smartphone size={19}/><div><strong>{permission==='granted'?'Alertas do sistema ativados':permission==='denied'?'Alertas bloqueados pelo aparelho':permission==='unsupported'?'Este navegador não oferece alertas':'Ativação necessária'}</strong><span>{permission==='denied'?'Libere as notificações nas configurações do navegador ou aparelho.':'Som personalizado funciona com o app aberto; fechado, será usado o som do sistema.'}</span></div></div><div className="preference-grid"><label className="preference-tile coral"><input type="checkbox" checked={preferences.enabled} onChange={e=>update({enabled:e.target.checked})}/><span className="preference-icon"><BellRing size={19}/></span><span><strong>Alertas visuais</strong><small>Notificação, balão no ícone e acesso à situação.</small></span></label><label className="preference-tile mint"><input type="checkbox" checked={preferences.vibration} onChange={e=>update({vibration:e.target.checked})}/><span className="preference-icon"><Smartphone size={19}/></span><span><strong>Vibração</strong><small>Usada em celulares compatíveis.</small></span></label></div><div className="device-sound-row"><label><span>Som com o app aberto</span><select value={preferences.sound} onChange={e=>update({sound:e.target.value as AlertSound})}><option value="soft">Suave</option><option value="chime">Campainha</option><option value="alarm">Despertador</option><option value="silent">Sem som</option></select></label><button type="button" className="secondary-button" onClick={()=>previewAlertSound(preferences.sound)}><Volume2 size={17}/>Testar som</button></div><div className="heading-actions">{permission!=='granted'&&permission!=='unsupported'&&<button type="button" className="primary-button" onClick={()=>void activate()}><BellRing size={17}/>Ativar alertas</button>}{!installed&&installPrompt&&<button type="button" className="secondary-button" onClick={()=>void install()}><Download size={17}/>Instalar aplicativo</button>}{installed&&<span className="mini-status success">Aplicativo instalado</span>}</div>{permission==='default'&&<p className="device-help">A pergunta de permissão aparece depois que você tocar em “Ativar alertas”.</p>}{!installed&&!installPrompt&&<p className="device-help">No iPhone/iPad: Compartilhar → Adicionar à Tela de Início. No computador ou Android, use “Instalar aplicativo” no menu do navegador.</p>}</div>
}
