import { useEffect, useState, type ChangeEvent } from 'react'
import { Image, Save, Upload } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Branding } from '../branding/BrandingProvider'

type AssetKey=Exclude<keyof Branding,'app_name'|'short_name'>
const assets:Array<{key:AssetKey;label:string;help:string;accept:string;surface:'light'|'dark'|'neutral';group:string}>=[
  {key:'full_logo_light_url',label:'Logo completa · fundo claro',help:'1200 × 400 px · transparente · textos escuros',accept:'image/png,image/webp,image/svg+xml',surface:'light',group:'Logos completas'},
  {key:'full_logo_dark_url',label:'Logo completa · fundo escuro',help:'1200 × 400 px · transparente · textos claros',accept:'image/png,image/webp,image/svg+xml',surface:'dark',group:'Logos completas'},
  {key:'menu_logo_light_url',label:'Logo compacta · fundo claro',help:'512 × 512 px · menu, cabeçalhos e telas claras',accept:'image/png,image/webp,image/svg+xml',surface:'light',group:'Menu e navegação'},
  {key:'menu_logo_dark_url',label:'Logo compacta · fundo escuro',help:'512 × 512 px · barra lateral e telas escuras',accept:'image/png,image/webp,image/svg+xml',surface:'dark',group:'Menu e navegação'},
  {key:'login_logo_light_url',label:'Logo do login · fundo claro',help:'1200 × 600 px · centralizada e com margem interna',accept:'image/png,image/webp,image/svg+xml',surface:'light',group:'Login'},
  {key:'login_logo_dark_url',label:'Logo do login · fundo escuro',help:'1200 × 600 px · alternativa para login escuro',accept:'image/png,image/webp,image/svg+xml',surface:'dark',group:'Login'},
  {key:'icon_light_url',label:'Ícone funcional · fundo claro',help:'512 × 512 px · símbolo sem o nome da marca',accept:'image/png,image/webp,image/svg+xml',surface:'light',group:'Ícones funcionais'},
  {key:'icon_dark_url',label:'Ícone funcional · fundo escuro',help:'512 × 512 px · símbolo claro e legível',accept:'image/png,image/webp,image/svg+xml',surface:'dark',group:'Ícones funcionais'},
  {key:'favicon_light_url',label:'Favicon · tema claro',help:'64 × 64 px · PNG ou ICO',accept:'image/png,image/x-icon',surface:'light',group:'Navegador e PWA'},
  {key:'favicon_dark_url',label:'Favicon · tema escuro',help:'64 × 64 px · PNG ou ICO',accept:'image/png,image/x-icon',surface:'dark',group:'Navegador e PWA'},
  {key:'app_icon_192_url',label:'Ícone do app · 192',help:'192 × 192 px · PNG quadrado',accept:'image/png',surface:'neutral',group:'Navegador e PWA'},
  {key:'app_icon_512_url',label:'Ícone do app · 512',help:'512 × 512 px · PNG quadrado para instalação',accept:'image/png',surface:'neutral',group:'Navegador e PWA'},
]

export function MasterBrandingPanel(){
  const[form,setForm]=useState<Branding|null>(null);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('')
  useEffect(()=>{void supabase.from('platform_branding').select('*').eq('id',1).single().then(({data,error})=>{if(error)setError(error.message);else setForm(data as Branding)})},[])
  async function upload(key:AssetKey,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file||!form)return;setBusy(key);setError('');const extension=file.name.split('.').pop()?.toLowerCase()||'png';const path=`${key}.${extension}`;const{error:uploadError}=await supabase.storage.from('platform-branding').upload(path,file,{upsert:true,cacheControl:'60'});if(uploadError){setError(uploadError.message);setBusy('');return}const{data}=supabase.storage.from('platform-branding').getPublicUrl(path);setForm({...form,[key]:`${data.publicUrl}?v=${Date.now()}`});setBusy('')}
  async function save(){if(!form)return;setBusy('save');setError('');setMessage('');const{error}=await supabase.from('platform_branding').upsert({id:1,...form,updated_at:new Date().toISOString()});if(error)setError(error.message);else setMessage('Identidade visual atualizada. Recarregue o app para visualizar em todas as áreas.');setBusy('')}
  if(!form)return <div className="panel-card">Carregando identidade visual...</div>
  return <div className="branding-admin"><div className="master-section-bar"><div><span className="eyebrow">IDENTIDADE VISUAL</span><h2>Biblioteca automática da marca</h2><p>Cadastre uma vez. O sistema escolhe a versão correta conforme o fundo e a função de cada tela.</p></div><button className="primary-button" disabled={busy==='save'} onClick={()=>void save()}><Save size={16}/>{busy==='save'?'Salvando...':'Salvar e aplicar'}</button></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<div className="panel-card branding-names"><label><span>Nome completo do aplicativo</span><input value={form.app_name} onChange={e=>setForm({...form,app_name:e.target.value})}/></label><label><span>Nome curto</span><input maxLength={20} value={form.short_name} onChange={e=>setForm({...form,short_name:e.target.value})}/></label></div><div className="branding-auto-note"><strong>Uso automático</strong><span>Claro usa arquivos “fundo claro”; barras escuras usam “fundo escuro”; instalação e atalhos usam os ícones PWA.</span></div>{[...new Set(assets.map(asset=>asset.group))].map(group=><section className="branding-group" key={group}><div className="branding-group-title"><span>{group}</span></div><div className="branding-assets-grid">{assets.filter(asset=>asset.group===group).map(asset=><article className="panel-card branding-asset" key={asset.key}><div className={`branding-preview surface-${asset.surface}`}>{form[asset.key]?<img src={form[asset.key]||''} alt={asset.label}/>:<Image size={34}/>}</div><div><h3>{asset.label}</h3><p>{asset.help}</p><label className="secondary-button branding-upload"><Upload size={15}/>{busy===asset.key?'Enviando...':'Escolher imagem'}<input type="file" hidden accept={asset.accept} disabled={Boolean(busy)} onChange={e=>void upload(asset.key,e)}/></label>{form[asset.key]&&<button className="text-action" onClick={()=>setForm({...form,[asset.key]:null})}>Remover</button>}</div></article>)}</div></section>)}</div>
}
